-- ================================================================
-- THE BLOWTORCH OF PARMA - TBOP v3 DATABASE ALIGNMENT
-- Designed to preserve existing data and the working admin login.
-- Run only if the v3 site reports a missing table/column.
-- ================================================================

create extension if not exists pgcrypto;

-- Keep the working admin table/function. Add missing compatibility fields only.
create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.site_admins add column if not exists active boolean not null default true;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.site_admins
    where user_id = auth.uid() and active is true
  );
$$;
grant execute on function public.is_site_admin() to authenticated;

-- NEWS: matches the table currently in use.
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);
alter table public.news add column if not exists published boolean not null default true;
alter table public.news add column if not exists created_at timestamptz not null default now();
alter table public.news add column if not exists updated_at timestamptz not null default now();
alter table public.news add column if not exists published_at timestamptz;

-- EVENTS: v3 intentionally uses starts_at for time. It does NOT use event_time.
create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  starts_at timestamptz,
  location text,
  visibility text,
  recurrence text,
  created_by uuid,
  created_at timestamptz not null default now(),
  event_date date
);
alter table public.events add column if not exists description text;
alter table public.events add column if not exists starts_at timestamptz;
alter table public.events add column if not exists location text;
alter table public.events add column if not exists created_by uuid;
alter table public.events add column if not exists created_at timestamptz not null default now();
alter table public.events add column if not exists event_date date;

-- DOCUMENTS: stable public PDF schema used by v3.
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null default 'Other',
  description text,
  file_url text,
  storage_path text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.documents add column if not exists category text not null default 'Other';
alter table public.documents add column if not exists description text;
alter table public.documents add column if not exists file_url text;
alter table public.documents add column if not exists storage_path text;
alter table public.documents add column if not exists published boolean not null default true;
alter table public.documents add column if not exists created_at timestamptz not null default now();

-- RLS. These policies are deliberately simple.
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.documents enable row level security;

-- Public reads
DROP POLICY IF EXISTS "TBOP v3 public news" ON public.news;
CREATE POLICY "TBOP v3 public news" ON public.news FOR SELECT TO anon, authenticated USING (published = true OR public.is_site_admin());
DROP POLICY IF EXISTS "TBOP v3 public events" ON public.events;
CREATE POLICY "TBOP v3 public events" ON public.events FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "TBOP v3 public documents" ON public.documents;
CREATE POLICY "TBOP v3 public documents" ON public.documents FOR SELECT TO anon, authenticated USING (published = true OR public.is_site_admin());

-- Admin writes
DROP POLICY IF EXISTS "TBOP v3 admin news" ON public.news;
CREATE POLICY "TBOP v3 admin news" ON public.news FOR ALL TO authenticated USING (public.is_site_admin()) WITH CHECK (public.is_site_admin());
DROP POLICY IF EXISTS "TBOP v3 admin events" ON public.events;
CREATE POLICY "TBOP v3 admin events" ON public.events FOR ALL TO authenticated USING (public.is_site_admin()) WITH CHECK (public.is_site_admin());
DROP POLICY IF EXISTS "TBOP v3 admin documents" ON public.documents;
CREATE POLICY "TBOP v3 admin documents" ON public.documents FOR ALL TO authenticated USING (public.is_site_admin()) WITH CHECK (public.is_site_admin());

grant select on public.news, public.events, public.documents to anon;
grant select, insert, update, delete on public.news, public.events, public.documents to authenticated;
-- News uses bigint identity; authenticated inserts need sequence permission.
grant usage, select on all sequences in schema public to authenticated;

-- PDF storage bucket and write policies.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('club-documents','club-documents',true,26214400,array['application/pdf'])
on conflict (id) do update set public=true,file_size_limit=26214400,allowed_mime_types=array['application/pdf'];
DROP POLICY IF EXISTS "TBOP v3 upload PDFs" ON storage.objects;
CREATE POLICY "TBOP v3 upload PDFs" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id='club-documents' AND public.is_site_admin());
DROP POLICY IF EXISTS "TBOP v3 delete PDFs" ON storage.objects;
CREATE POLICY "TBOP v3 delete PDFs" ON storage.objects FOR DELETE TO authenticated USING (bucket_id='club-documents' AND public.is_site_admin());

notify pgrst, 'reload schema';
